apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dremio-executor
spec:
  serviceName: "dremio-executor"
  replicas: {{.Values.executor.count}}
  selector:
    matchLabels:
      app: dremio-executor
  template:
    metadata:
      labels:
        app: dremio-executor
    spec:
      containers:
      - name: dremio-executor
        image: {{.Values.image}}
        env:
        - name: DIST_PATH
          valueFrom:
            configMapKeyRef:
              name: dremio-config
              key: paths.dist
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          valueFrom:
            configMapKeyRef:
              name: dremio-config
              key: coordinator.memory.heap
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          valueFrom:
            configMapKeyRef:
              name: dremio-config
              key: coordinator.memory.direct
        - name: LOCAL_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["/opt/dremio/bin/dremio"]
        args:
        - "start-fg"
        - ""
        - "-Dzookeeper=zk-hs:2181"
        - "-Dregistration.publish-host=$(LOCAL_POD_IP)"
        - "-Dservices.coordinator.enabled=false"
        - "-Dpaths.dist=$(DIST_PATH)"
        ports:
        - containerPort: 45678
          name: server
      initContainers:
      - name: wait-for-zk
        image: busybox
        command:  ["sh", "-c", "until nc -z zk-hs 2181; do echo waiting for zookeeper; sleep 2; done;"]
